import "./components/index"
import "./components/sliders"
import "./components/lazyImg"
import "./components/appHeight"
import "./components/newrubkoff/nbl-cookies"

import "./components/dom/d-header"
import "./components/dom/smooth-scroll"
import "./components/dom/popups"
import "./components/dom/card-small"
import "./components/dom/fixed-block"
import "./components/dom/filter-popup"
import "./components/dom/text-truncate"
import "./components/dom/page-house-slider"
import "./components/dom/layer-map"
import "./components/dom/filter-links"
import "./components/dom/marquee"
import "./components/dom/rent-page"
import "./components/dom/copy"

